# Basic Information 
title: Dr. Yang Yan
position: Postdoctoral Researcher
affiliation: Freie Universität Berlin
#affiliation_link: https://www.geschkult.fu-berlin.de/e/oas/sinologie/institut/mitarbeiter/3_mitarbeiter/Yan.html
#affiliation_logo: https://raw.githubusercontent.com/yangyan0925/homepage/main/assets/img/fu.svg
email: yang.yan@fu-berlin.de

# Search Engine Optimization (SEO)
keywords: yang yan, yan yang, yangyan, yanyang
canonical: https://github.com/yangyan0925/homepage/
description: Yang Yan is a postdoctoral researcher specializing in political science and public administration.

# The option is used to enable the Johns Hopkins template.
enable_hopkins_logo: false

# The option is used to show the last update time.
enable_last_update: false

# Links
link_type: icon #text/icon
google_scholar: https://scholar.google.com.hk/citations?hl=zh-CN&pli=1&user=Z1F1vLgAAAAJ
cv_link: https://raw.githubusercontent.com/yangyan0925/homepage/main/assets/file/CV_YangYAN202411.pdf
# github_link: https://github.com/yaoyao-liu/
linkedin: https://www.linkedin.com/in/%E9%98%B3-%E7%87%95-684914296/
twitter: https://x.com/yanyang_1992

# Images 
avatar: https://raw.githubusercontent.com/yangyan0925/homepage/main/assets/img/yangyan2021.png


# Footnotes
# footnote: Feel free to use my website's source code.
# footnote_link: https://github.com/yaoyao-liu/minimal-light

# Analytics
# Please remove the following lines about analytics services if you fork my project. 
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.
# clustrmaps_id: CJD8XwsJhSyQ6sbsU-Gw0cNcUlbah7KW3xvHN2QlwW0

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
