# Basic Information 
title: Yang Yan
position: Assistant Professor
affiliation: Tongji University
#affiliation_link: https://www.geschkult.fu-berlin.de/e/oas/sinologie/institut/mitarbeiter/3_mitarbeiter/Yan.html
#affiliation_logo: https://raw.githubusercontent.com/yangyan0925/homepage/main/assets/img/fu.svg
email: yanyang0925@tongji.edu.cn

# Search Engine Optimization (SEO)
url: "https://yang-yan.com"
baseurl: ""
keywords: Yang Yan, Yang Yan Tongji University, Yang Yan political science, Yang Yan public administration, 燕阳, 同济大学
canonical: https://yang-yan.com/
description: Yang Yan is an Assistant Professor at Tongji University specializing in elite politics, bureaucratic politics, political communication, issue attention, and digital governance.

# The option is used to enable the Johns Hopkins template.
enable_hopkins_logo: false

# The option is used to show the last update time.
enable_last_update: false

# Links
link_type: icon #text/icon
google_scholar: https://scholar.google.com.hk/citations?hl=zh-CN&pli=1&user=Z1F1vLgAAAAJ
cv_link: https://raw.githubusercontent.com/yangyan0925/homepage/main/assets/file/CV202604.pdf
# github_link: https://github.com/yaoyao-liu/
# linkedin: https://www.linkedin.com/in/%E9%98%B3-%E7%87%95-684914296/
twitter: https://x.com/yanyang_1992

# Images 
avatar: https://raw.githubusercontent.com/yangyan0925/homepage/main/assets/img/YY202604.JPG


# Footnotes
# footnote: 
# footnote_link:


# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
